# -*- coding: utf-8 -*-
# Code generated by DeepSeek-R1, 2026.
# Modified by Mosha Huyan, under CC BY-NC-SA 4.0, 2026.

from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
import json
import os

app = Flask(__name__)
CORS(app)  # 允许跨域（方便本地测试）

# 模拟数据库：有效凭证列表（生产环境应使用真实数据库）
# 预置几个有效的激活码用于演示
VALID_CODES = {
    "a648a75127fba32fa03088c6346897e81ffad0e78f16bd9802d327cb4bd35341": "3992/7/8",
    "8d084b3b93d64d599b2c5ac2d535ff40e265a679e5c2f99cc455b6b93aa717ad": "3992/8/8",
    "ddba4d9b0ce996d6ef535f5451f5b0fa6d23e4495d63313dc45fa1e2dff41a7c": "3991/60/42",
    "07ba42278f51fe2d4ab86c8ab2349b4de1cd2a9056e68e31ecf0c9f5f7671785": "3992/4/20",
    "86ff4e4b80d064e78c32c9dcd7c5dd8c4f3fb709a30959b3b7392243c5538563": "3999/60/42",
    "e7e2e15d8e4677d287c5656d4f612ea1e385b40089dcf3d8f1833f1dfbaa7c2c": "3993/1/42",
    "3fbe5f08e92649e0916ddf4757842d154dc17479bab302593117402190bdf904": "3992/7/7",
    "4547224c2e6ea805df2623da69156d116d01ac7e353655b449359c141918b466": "3992/6/3", 
    "3acfb8f4700b4c8d9b205e5cffd049a3557768387224e55cdadb983bbc2ae5a4": "3993/12/42",
}

# 存储已使用的凭证（防止重复激活）
USED_CODES_FILE = "used_codes.json"

def load_used_codes():
    if os.path.exists(USED_CODES_FILE):
        with open(USED_CODES_FILE, "r", encoding="utf-8") as f:
            return set(json.load(f))
    return set()

def save_used_code(code):
    used = load_used_codes()
    used.add(code)
    with open(USED_CODES_FILE, "w", encoding="utf-8") as f:
        json.dump(list(used), f, ensure_ascii=False, indent=2)

@app.route("/api/verify", methods=["POST"])
def verify():
    data = request.get_json()
    code = data.get("code", "").strip()

    if not code:
        return jsonify({"valid": False, "message": "凭证不能为空。"})

    # 检查是否已被使用
    used = load_used_codes()
    if code in used:
        return jsonify({"valid": False, "message": "该凭证已被使用。"})

    # 检查是否有效
    if code in VALID_CODES:
        expiry = VALID_CODES[code]
        # 标记为已使用
        save_used_code(code)
        return jsonify({
            "valid": True,
            "message": "激活成功。",
            "expiry": expiry
        })
    else:
        return jsonify({"valid": False, "message": "无效的凭证，请检查后重新输入。"})

@app.route("/api/status", methods=["GET"])
def status():
    """检查服务状态（可选）"""
    return jsonify({"status": "running", "valid_codes_count": len(VALID_CODES)})

@app.route('/')
def index():
    return send_from_directory('.', 'AI2.html')

@app.route('/<path:path>')
def static_files(path):
    return send_from_directory('.', path)

if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)